name: radiant-ble-controller
version: '0.0.5.0'
summary: radiant ble controller service
description: seperated radiant ble controller from mono
grade: stable # devel or stable
confinement: strict

parts:
  my-service:
    plugin: dump
    source: src/
    build-attributes: [keep-execstack]
    override-prime: |
      snapcraftctl prime
      echo "running POST script"
      echo "${SNAPCRAFT_PROJECT_VERSION}" > bin/version.txt
      chmod +x bin/radiant-ble-controller

apps:
  controllerd:
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:/lib/arm-linux-gnueabihf
    command: controllerd
    plugs:
      - network
      - network-bind
      - bluetooth-control
      - network-control
    daemon: simple
