#!/bin/sh -e

logger "*** start install hook ***"

### variables ###
LOGDIR="${SNAP_COMMON}/Logs"
CONFIGDIR="${SNAP_COMMON}/Config"
TAGDIR="${SNAP_COMMON}/Data/TagStateLog"
TAGSUMDIR="${SNAP_COMMON}/Data/TagReadSummaryLog"


#### main ####
# setup our working directory
mkdir -p $LOGDIR
mkdir -p $CONFIGDIR
mkdir -p $TAGDIR
mkdir -p $TAGSUMDIR

# check to see if the default.config already exist
if [ ! -f ${CONFIGDIR}/default.config ]; then
  logger "did not find default.config at this location ${CONFIGDIR}"
  logger "copying it from snap"
  cp ${SNAP}/misc-files/default.config ${CONFIGDIR}/
fi

logger "*** end install hook ***"