#!/bin/sh -e

logger "*** start install hook ***"

### variables ###
LOGDIR="${SNAP_COMMON}/Logs"
CONFIGDIR="${SNAP_COMMON}/Config"
TAGDIR="${SNAP_COMMON}/Data/TagStateLog"
TAGSUMDIR="${SNAP_COMMON}/Data/TagReadSummaryLog"


#### main ####
# setup our working directory
mkdir -p $LOGDIR
mkdir -p $CONFIGDIR
mkdir -p $TAGDIR
mkdir -p $TAGSUMDIR

# copy the default.config 
logger "copying default.config from snap"
cp ${SNAP}/misc-files/default.config ${CONFIGDIR}/

logger "*** end install hook ***"
